language: java
jdk:
- openjdk7
sudo: required
services:
- docker
env:
  DOCKER_USERNAME:
    secure: D+kIFjKMvje1qEuyjeceG8z+bhxurGW7MN9QGSs4hSc0ITspPBU0LHZuRDl7Ji/LwM0cZjdknz4K0NCTnM9m+giaCjcChNCyexLIryEHR++BiN3wYpZjgg4yY4phlIGcqGZn8QRmz4+lVH08Fsrpjm9pYyJXQ0QSA6aStjR1MuUKD9nAYz3I5LW3SRgxnifjdr8wJ7PypL8zBYniSn0ekVJSgu0Zqg5i5zZsNszU+oLvHDZ2zMfoCM8+yudGOimxgm6DjrBk7TG8QqGl+mlRDyJB+TBOkyOYUz/Cohfb7OjdMudwUu9C32tAUIwdlqtL1mLJHJFkiWDkNeLJmzirQWn4ZevkchjrNIY7XjErrwWv7euakm9POIqdG8yAQPmJCzTP3bWo2QzNlYnDubCFeCKXQJAwrByCgdaUY87o2uvbjO+qqEyiTa0+8+tjrJjoLXLGmqB2aEPWz6sgDtb2iCXt2JyS3Qfym1VZNO9LiwDQuTcjwQ94KMI6gNRg3kUa8i6V6Fm3lRa3iQJpE3P2fcaqgj+Pvi70BJgu2WQ1l3IjFkM/V3orHnuoY8YJ/Hef7y8ZYrouDwZdMWvEKnpmCf0ovvFpM9p99MZkbIk/DauHFrGtyvMUSRpKNCG6Ruzm3YDqXwBBsYTzMueMeBeICxeRBSjqWORrzpIx/ILWaqc=
  DOCKER_PASSWORD:
    secure: CWpwz1YNmwqWhvOwU6hdrKhsJxxsF/UhGwUfT5V9BwBw0DV/jNGxGyncnt3Lfr60y1rV8Zn0hkJ9DNxyi9+XQ01ppyIJsfKI4G3oERv8C5REJMvThQevSbezZD/ljO1f4qsnNHC24Q5+x2Z/ife0e2CFzc7fdg4LkMTN/YR6QrrvE2A+Dde1zANgrtEQWdecfOHYRjSBbxzSzrXniaj5Bk+UBaRRohtqwitk4FHY9l6e/gR+qE2on34+DXEmPJ1eM7cICY04TddJgcMe4vNeWt5r0Bv3NkfZtYRjKVvcuK+3nGVPqfSa4njnBYpb9TiFd/sbpwAFYfcx7SL7WqNwRK3+gYG4B/Qu8TmPD8RIZ3Jm4Gou40CIkmeAuqylDGrJOTs6qMG8plZXoJzpL/l42fsrS4D0q8tDZ553MQNEuERsf9NypX1C45LFDHTZKqmqVMf70ZoyHQa+EWtJraHkFRe89TFxPyqLy4F8vhA75LG7xa0Q+3RnMPMQk2AifsLPJS+UjzUY4Qs158Uy8mM+nuhy6Jia4FsgobazruLb3/IUb6W5alBT2+7jZP5ZjB5qw9PfkOvg1GEr08Yo6BMAAW5cUfk5sIdBIQUOPtKqoBuhXq8HfCF/YCoU9GXSj5R5H5IGUTtRf5mgu+W8fDAr2sszrdAhHmAekAnGtVsqzWc=
install:
- mvn clean install
deploy:
  provider: releases
  api_key:
    secure: bqcGbyzBGYRpnmyNjaKsU2Co8HkGkmET0XWkKPdoMX4fWifI52CMXGjidIWapTBs60eCu3ypbPJQUeaXKOfOWDX20pWrDaKeWdXjZWNKGB/QttgwDvzJvZJrK69qL+/m4jn2upI22F2UIYzCOjw9HhCrdkBPZSoWU7e1U0rVAwC6SKUK10tR7tb/XgmlRvieJoiGj5XoEwZCujTJkNAFYr5M2L9ZIE7I994ieYeUClmG0Oja1xOReJI3WR9CxYHpcj8D/PpbajDArdimPfhE/ZgVJZgf3Aj2TpqCYYBUJ29ABw8pGZvP7cQNXMXK+fAqCZIEl+M5rNDhMHiY7zGBqBi0tg3LY3qMoT5d0O4rnpZ4mshybK8R5Y8MfnWV7TDcJTuxcwfLrn6biWtX0bJPqYCOeMLWfd8E+lPWEC92sgmTj2VULkkehH2bUpG/xFD9eqQyGmz3GrxAwf2rPKE9SDT8DC0MSNTSu+yYRs1rMRHAibHb6rpZ3eHyUHYuYN0PGGYq7ey2fjqJL/3/56v5/S+hJ2rC8/ERhvHZxLkzLUUFEDdFI/n0X6Yns7GdF1KAnlWyNE/qgoDvIZvSxOJR7WouQ1ojsxgDMLpHIlmsRUt8jgqjM+YHbfdbSsIbU+Kv/4FdYl0NvWgMjjbfpX7lQCpI35dHh2Pv3CwoHF0ZCZ4=
  file: "./target/simple-web-app.war"
  on:
    repo: flaresolar/simple-web-app
    tags: true
after_deploy:
  - docker build . -t flare/simple-web-app:"$TRAVIS_TAG"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push flare/simple-web-app:$TRAVIS_TAG