language: java
jdk:
- openjdk7
sudo: required
services:
- docker
install:
- mvn clean install
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bqcGbyzBGYRpnmyNjaKsU2Co8HkGkmET0XWkKPdoMX4fWifI52CMXGjidIWapTBs60eCu3ypbPJQUeaXKOfOWDX20pWrDaKeWdXjZWNKGB/QttgwDvzJvZJrK69qL+/m4jn2upI22F2UIYzCOjw9HhCrdkBPZSoWU7e1U0rVAwC6SKUK10tR7tb/XgmlRvieJoiGj5XoEwZCujTJkNAFYr5M2L9ZIE7I994ieYeUClmG0Oja1xOReJI3WR9CxYHpcj8D/PpbajDArdimPfhE/ZgVJZgf3Aj2TpqCYYBUJ29ABw8pGZvP7cQNXMXK+fAqCZIEl+M5rNDhMHiY7zGBqBi0tg3LY3qMoT5d0O4rnpZ4mshybK8R5Y8MfnWV7TDcJTuxcwfLrn6biWtX0bJPqYCOeMLWfd8E+lPWEC92sgmTj2VULkkehH2bUpG/xFD9eqQyGmz3GrxAwf2rPKE9SDT8DC0MSNTSu+yYRs1rMRHAibHb6rpZ3eHyUHYuYN0PGGYq7ey2fjqJL/3/56v5/S+hJ2rC8/ERhvHZxLkzLUUFEDdFI/n0X6Yns7GdF1KAnlWyNE/qgoDvIZvSxOJR7WouQ1ojsxgDMLpHIlmsRUt8jgqjM+YHbfdbSsIbU+Kv/4FdYl0NvWgMjjbfpX7lQCpI35dHh2Pv3CwoHF0ZCZ4=
  file: "./target/simple-web-app.war"
  on:
    repo: flaresolar/simple-web-app
    tags: true
after_deploy:
- docker build . -t flare/simple-web-app:"$TRAVIS_TAG"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PWD"
- docker push flare/simple-web-app:$TRAVIS_TAG
env:
  global:
    secure: OcGyC+NGR60ccJ+ID6HmqSXhttW4cpsh7F0mKv+d5l1/TcYYri4A3fVglTpudTVSyw9277J86wXawN+pq07xaNzKhsmwyajSgV4MhqNeDEMNCynKRHbW1C7+XXcITBuJq/wJJ+G6PIShcPFx+dKGIVwTqa30EZU0EkCV7lK7w2BUG7EwQji6JcNdYxbf4M16e5Ep5n4P3oLIEkZFDOE1GN88CmTynxhntv3793/0LRvQqTQPBkAB6z/QM3lwPljFKtbbLyTFFZ4Tsd9KxyVI+IV5Wjc9yvFlwjm/pJjbs6PQ9c2Pu6CsTiSg1VXU2d7WROgIZisqMCwPKTeLGKZj4+4eyG/wCFmG7/jmbEJehp12Y9Y4SPwEpfm1pi+PqMJEQtjih0N5953HXrrUh4DTv+2trfOhW2Ajg6+50o1c4Lnn1NqzfQ6HrSuZonyqp5tB3SVKANEkBtetO1iI5sTgyS1Uuj1Ol9oJLokVx1MX1rNwePoSLpEvxl5yCZ0Qg+8+eNOdfH+bnJrIivGQAerGU4HH1gYpzrCvelgWjt6qFPIZabqeDlKg+FZQhbHQs/KHmHEKlEDA7xsuLKaWtrAL0bKGw7giT5XOHPfBMeRD+TMINnWsjG/FXuosag3sB0EWeHGDq2Dix6mG9Jdoc8MkDN9eDd5mFJxSSFFcu1A46bw=
