language: java
jdk:
- openjdk7
sudo: required
services:
- docker
env:
  global:
    secure: WtUWx/JTAZAQbrfEVV37wQKfLU23WnZBJ4ZqopcOKWugJ3FUuP0nzkrXn7xbggEv5ZHHqNUhacUdFvf4cmTirPH6gPU9KDEs6uG5Xk1gORcUNnZe97/QIKHFZA4e7Xsj3JDrM7U0AT6l+adoqlM0x6B7vauluqz6f3sgAlnbMgM5hNsdPUCzONjAFDIFCJrvVGdES5oE2cki0kqZbgYfuARgPC32lEWK9DugPFhBKHdrmRI/e3/BjUUEWFZRC7fPZMgWbRtWRa6GT5mAcQY62bnxr5lCg/FKSwRBTu8ewwnyIN+RYhLP8RT0765ssOFL/6xmpybaZ7sCL94qBBq70smrd6NroH/QWq8aRGdzfs7GeZPGF1EHfR4Es2mH87PODt9HkddKaRcTSCmbIop+6cAYLvkwHo07utoZlwYdpd2mWbce58h4oBpwJp5I2XUgxXPsTqTvxHuCR9nHsWsvOovPJjHCFT9gMlAg8sEBG9nYbjVEYSPpknJ5D4tWqNi3zgujvksMfbQzI47E2JubIcgP81sdiCDV/oNC05B4wqObxbsR9CELKF7igieC/E25x9YQsaJtu+TY8UfYUuD2ztp/12dSwNCX1iYJyakO4GQ79IWrBpUSR1jA/I18OmkAZDuKy6uOlQnONChzsXCvcE2OPLtOEmpdlwE/VcKam9c=
install:
  - echo "dockhub_user: \"$DOCKER_USERNAME\""
  - mvn clean install
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bqcGbyzBGYRpnmyNjaKsU2Co8HkGkmET0XWkKPdoMX4fWifI52CMXGjidIWapTBs60eCu3ypbPJQUeaXKOfOWDX20pWrDaKeWdXjZWNKGB/QttgwDvzJvZJrK69qL+/m4jn2upI22F2UIYzCOjw9HhCrdkBPZSoWU7e1U0rVAwC6SKUK10tR7tb/XgmlRvieJoiGj5XoEwZCujTJkNAFYr5M2L9ZIE7I994ieYeUClmG0Oja1xOReJI3WR9CxYHpcj8D/PpbajDArdimPfhE/ZgVJZgf3Aj2TpqCYYBUJ29ABw8pGZvP7cQNXMXK+fAqCZIEl+M5rNDhMHiY7zGBqBi0tg3LY3qMoT5d0O4rnpZ4mshybK8R5Y8MfnWV7TDcJTuxcwfLrn6biWtX0bJPqYCOeMLWfd8E+lPWEC92sgmTj2VULkkehH2bUpG/xFD9eqQyGmz3GrxAwf2rPKE9SDT8DC0MSNTSu+yYRs1rMRHAibHb6rpZ3eHyUHYuYN0PGGYq7ey2fjqJL/3/56v5/S+hJ2rC8/ERhvHZxLkzLUUFEDdFI/n0X6Yns7GdF1KAnlWyNE/qgoDvIZvSxOJR7WouQ1ojsxgDMLpHIlmsRUt8jgqjM+YHbfdbSsIbU+Kv/4FdYl0NvWgMjjbfpX7lQCpI35dHh2Pv3CwoHF0ZCZ4=
  file: "./target/simple-web-app.war"
  on:
    repo: flaresolar/simple-web-app
    tags: true
after_deploy:
- docker build . -t flare/simple-web-app:"$TRAVIS_TAG"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push flare/simple-web-app:$TRAVIS_TAG
